// Valores de bateria
#define PORCENTAJE_MAX_BATERIA 100
#define PORCENTAJE_MIN_BATERIA 0

// Timeouts
#define TIEMPO_VERIFICACION_BATERIA_MS 10000

// Valores de dominio
#define CONSTANTE_CORRECCION_VOLTAJE_BATERIA 3.3 / 4095