// Configurar el PWM
#define FREQ 30000
#define RESOLUTION 8
#define PWM_CHANNEL_MOTOR 14

// Valores de dominio
#define MAXIMA_CANTIDAD_GIROS 4

// Tiempos delays
#define TIEMPO_DELAY_GIRO_MUY_CORTO_MS 0.1 * 1000
#define TIEMPO_DELAY_GIRO_CORTO_MS 0.2 * 1000
#define TIEMPO_DELAY_GIRO_LARGO_DERECHA_MS 0.3 * 1000
#define TIEMPO_DELAY_GIRO_LARGO_IZQUIERDA_MS 0.6 * 1000
#define TIEMPO_DELAY_ADELANTE_GIRO_MS 1 * 1000
#define TIEMPO_DELAY_RETROCEDER_MS 0.1 * 1000
#define TIEMPO_DELAY_PARAR_MS 0.5 * 1000

#define TIEMPO_DELAY_GIRO_MS 0.1 * 1000
#define TIEMPO_DELAY_ADELANTE_MS 0.2 * 1000

// Velocidades
#define VELOCIDAD_ROBOT 175

// Codificacion direccion
#define PARAR 0
#define ADELANTE 1
#define ATRAS 2
#define IZQUIERDA 3
#define DERECHA 4
#define ADELANTE_GIRO 5
#define ADELANTE_DERECHA 6
#define ADELANTE_IZQUIERDA 7