// Sensores distancia
#define PIN_SENSOR_DISTANCIA_ADELANTE 39
#define PIN_SENSOR_DISTANCIA_IZQUIERDA 36
#define PIN_SENSOR_DISTANCIA_DERECHA 34

#define PIN_TRIG_QUIMICO 18
#define PIN_ECHO_QUIMICO 19

// Motores
#define PIN_MOTOR_IZQUIERDA_EN 32
#define PIN_MOTOR_IZQUIERDA_IN1 33
#define PIN_MOTOR_IZQUIERDA_IN2 25
#define PIN_MOTOR_DERECHA_IN3 26
#define PIN_MOTOR_DERECHA_IN4 27
#define PIN_MOTOR_DERECHA_EN 14

// LED
#define PIN_LED_WIFI 2

// Bomba agua
#define PIN_BOMBA_AGUA 4

// Babtería
#define PIN_BATERIA 35