// Sensores distancia
#define PIN_TRIG_ADELANTE 12
#define PIN_ECHO_ADELANTE 13

#define PIN_TRIG_DERECHA 23
#define PIN_ECHO_DERECHA 22

#define PIN_TRIG_QUIMICO 18
#define PIN_ECHO_QUIMICO 19

// Motores
#define PIN_MOTOR_IZQUIERDA_EN 32
#define PIN_MOTOR_IZQUIERDA_IN1 33
#define PIN_MOTOR_IZQUIERDA_IN2 25
#define PIN_MOTOR_DERECHA_IN3 26
#define PIN_MOTOR_DERECHA_IN4 27
#define PIN_MOTOR_DERECHA_EN 14

// LED
#define PIN_LED_WIFI 2

// Bomba agua
#define PIN_BOMBA_AGUA 4